import Lax56Proofs.HKBBlocking
import Mathlib.Analysis.Convex.Between
import Mathlib.Analysis.Convex.Combination
import Mathlib.Analysis.Convex.Extreme
import Mathlib.Tactic

/-!
The three-colour triangle obstruction in the direct
Hujter--Kisfaludi-Bak argument.

The geometric part is phrased in terms of the oriented-area functional
`turn`.  This makes the supporting-face steps explicit and keeps the proof
independent of a diagram.
-/

namespace Lax56Proofs.HKBTriangle

open Lax56.Geometry
open Lax56Proofs.HKBBlocking
open Lax56Proofs.HKBConvexity
open Lax56Proofs.HKBGeometry
open Lax56Proofs.Orientation

/-- The closed convex triangle generated by three points. -/
noncomputable def triangleHull (a b c : Point) : Set Point :=
  convexHull ℝ ({a, b, c} : Set Point)

theorem vertex_mem_triangleHull (a b c : Point) :
    a ∈ triangleHull a b c := by
  exact subset_convexHull ℝ _ (by simp [triangleHull])

/-- A linear half-plane containing all generators contains their convex
hull. -/
theorem turn_nonneg_of_mem_convexHull
    {a b : Point} {A : Set Point} {p : Point}
    (hA : ∀ q ∈ A, 0 ≤ turn a b q)
    (hp : p ∈ convexHull ℝ A) :
    0 ≤ turn a b p := by
  let H : Set Point := {q | 0 ≤ turn a b q}
  have hconv : Convex ℝ H := by
    intro x hx y hy u v hu hv huv
    change 0 ≤ turn a b (u • x + v • y)
    rw [turn_convex_combo _ _ _ _ _ _ huv]
    exact add_nonneg (mul_nonneg hu hx) (mul_nonneg hv hy)
  exact convexHull_min hA hconv hp

theorem turn_nonpos_of_mem_convexHull
    {a b : Point} {A : Set Point} {p : Point}
    (hA : ∀ q ∈ A, turn a b q ≤ 0)
    (hp : p ∈ convexHull ℝ A) :
    turn a b p ≤ 0 := by
  have hnonneg : ∀ q ∈ A, 0 ≤ turn b a q := by
    intro q hq
    have hswap : turn b a q = -turn a b q := by
      simp [turn]
      ring
    rw [hswap]
    exact neg_nonneg.mpr (hA q hq)
  have := turn_nonneg_of_mem_convexHull hnonneg hp
  have hswap : turn b a p = -turn a b p := by
    simp [turn]
    ring
  rw [hswap] at this
  exact neg_nonneg.mp this

/-- The three oriented side inequalities of a positively oriented triangle
hold throughout its convex hull. -/
theorem triangle_edge_nonneg
    {a b c p : Point} (habc : 0 ≤ turn a b c)
    (hp : p ∈ triangleHull a b c) :
    0 ≤ turn a b p ∧ 0 ≤ turn b c p ∧ 0 ≤ turn c a p := by
  constructor
  · apply turn_nonneg_of_mem_convexHull
      (A := ({a, b, c} : Set Point)) (p := p)
    · intro q hq
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
      rcases hq with rfl | rfl | rfl
      · simp
      · simp
      · exact habc
    · exact hp
  constructor
  · apply turn_nonneg_of_mem_convexHull
      (A := ({a, b, c} : Set Point)) (p := p)
    · intro q hq
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
      rcases hq with rfl | rfl | rfl
      · simpa [turn_rotate] using habc
      · simp
      · simp
    · exact hp
  · apply turn_nonneg_of_mem_convexHull
      (A := ({a, b, c} : Set Point)) (p := p)
    · intro q hq
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
      rcases hq with rfl | rfl | rfl
      · simp
      · convert habc using 1 <;> simp only [turn] <;> ring
      · simp
    · exact hp

/-- A convex hull generated inside a convex set remains inside it. -/
theorem triangleHull_subset_of_mem
    {a b c : Point} {C : Set Point} (hC : Convex ℝ C)
    (ha : a ∈ C) (hb : b ∈ C) (hc : c ∈ C) :
    triangleHull a b c ⊆ C := by
  apply convexHull_min
  · intro p hp
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hp
    rcases hp with rfl | rfl | rfl <;> assumption
  · exact hC

/-- A supporting functional with a unique zero generator exposes that
generator in a finite convex hull. -/
theorem eq_of_mem_convexHull_of_unique_turn_zero
    {a b x q : Point} {A : Finset Point}
    (hqA : q ∈ A)
    (hA : ∀ p ∈ A, 0 ≤ turn a b p)
    (hunique : ∀ p ∈ A, turn a b p = 0 → p = q)
    (hx : x ∈ convexHull ℝ (A : Set Point))
    (hxzero : turn a b x = 0) :
    x = q := by
  classical
  obtain ⟨w, hw0, hw1, hwcenter⟩ := (Finset.mem_convexHull').mp hx
  have hwother : ∀ p ∈ A, p ≠ q → w p = 0 := by
    intro p hp hpq
    have hpturn : 0 < turn a b p := by
      have hn : turn a b p ≠ 0 := fun hz ↦ hpq (hunique p hp hz)
      exact lt_of_le_of_ne (hA p hp) (Ne.symm hn)
    exact weight_eq_zero_of_turn_pos a b x A w hw0 hw1 hwcenter
      hxzero hA hp hpturn
  have hwq : w q = 1 := by
    rw [← hw1]
    symm
    apply Finset.sum_eq_single q
    · intro p hp hpq
      exact hwother p hp hpq
    · exact fun h ↦ (h hqA).elim
  calc
    x = ∑ p ∈ A, w p • p := hwcenter.symm
    _ = w q • q := by
      apply Finset.sum_eq_single q
      · intro p hp hpq
        rw [hwother p hp hpq, zero_smul]
      · exact fun h ↦ (h hqA).elim
    _ = q := by rw [hwq, one_smul]

/-- Three distinct points of one colour cannot be collinear in a properly
blocked set with no four collinear points. -/
theorem not_collinear_of_same_colour
    {k : ℕ} {B : Finset Point} (hfour : ¬HasFourCollinear B)
    {colour : B → Fin k} (hproper : ProperBlocking B colour)
    {x y z : B} (hxy : x ≠ y) (hyz : y ≠ z) (hzx : z ≠ x)
    (hcxy : colour x = colour y) (hcyz : colour y = colour z) :
    ¬Collinear ℝ ({(x : Point), (y : Point), (z : Point)} : Set Point) := by
  intro hcol
  rcases hcol.wbtw_or_wbtw_or_wbtw with h | h | h
  · have hs : Sbtw ℝ (x : Point) (y : Point) (z : Point) :=
      ⟨h, Subtype.val_injective.ne hxy.symm, Subtype.val_injective.ne hyz⟩
    have hopen : (y : Point) ∈ openSegment ℝ (x : Point) (z : Point) := by
      rw [openSegment_eq_image_lineMap]
      exact hs.mem_image_Ioo
    exact no_same_colour_between hfour hproper hzx.symm hcxy hcyz hopen
  · have hs : Sbtw ℝ (y : Point) (z : Point) (x : Point) :=
      ⟨h, Subtype.val_injective.ne hyz.symm, Subtype.val_injective.ne hzx⟩
    have hopen : (z : Point) ∈ openSegment ℝ (y : Point) (x : Point) := by
      rw [openSegment_eq_image_lineMap]
      exact hs.mem_image_Ioo
    exact no_same_colour_between hfour hproper hxy.symm
      hcyz (hcxy.trans hcyz).symm hopen
  · have hs : Sbtw ℝ (z : Point) (x : Point) (y : Point) :=
      ⟨h, Subtype.val_injective.ne hzx.symm, Subtype.val_injective.ne hxy⟩
    have hopen : (x : Point) ∈ openSegment ℝ (z : Point) (y : Point) := by
      rw [openSegment_eq_image_lineMap]
      exact hs.mem_image_Ioo
    exact no_same_colour_between hfour hproper hyz.symm
      (hcxy.trans hcyz).symm hcxy hopen

/-- Three distinct equally coloured points have nonzero oriented area. -/
theorem turn_ne_zero_of_same_colour
    {k : ℕ} {B : Finset Point} (hfour : ¬HasFourCollinear B)
    {colour : B → Fin k} (hproper : ProperBlocking B colour)
    {x y z : B} (hxy : x ≠ y) (hyz : y ≠ z) (hzx : z ≠ x)
    (hcxy : colour x = colour y) (hcyz : colour y = colour z) :
    turn (x : Point) (y : Point) (z : Point) ≠ 0 := by
  intro hz
  apply not_collinear_of_same_colour hfour hproper hxy hyz hzx hcxy hcyz
  have hzline : (z : Point) ∈ affineSpan ℝ {(x : Point), (y : Point)} :=
    mem_line_of_turn_eq_zero (Subtype.val_injective.ne hxy) hz
  have hcol :
      Collinear ℝ ({(z : Point), (x : Point), (y : Point)} : Set Point) :=
    collinear_insert_of_mem_affineSpan_pair hzline
  convert hcol using 1 <;> ext p <;> simp [or_comm, or_left_comm]

/-- Three distinct points of one colour. -/
def MonoTriple {k : ℕ} {B : Finset Point} (colour : B → Fin k)
    (a b c : B) : Prop :=
  a ≠ b ∧ b ≠ c ∧ c ≠ a ∧
    colour a = colour b ∧ colour b = colour c

noncomputable def triangleCount (B : Finset Point) (a b c : Point) : ℕ := by
  classical
  exact (B.filter fun p ↦ p ∈ triangleHull a b c).card

theorem triangleHull_swap_last (a b c : Point) :
    triangleHull a c b = triangleHull a b c := by
  unfold triangleHull
  congr 1
  ext p
  simp [or_comm, or_left_comm]

theorem triangleHull_rotate (a b c : Point) :
    triangleHull b c a = triangleHull a b c := by
  unfold triangleHull
  congr 1
  ext p
  simp [or_comm, or_left_comm]

/-- A finite nonempty family of monochromatic triples has a member whose
closed triangle contains the minimum possible number of points of `B`. -/
theorem exists_minimal_monoTriple
    {k : ℕ} {B : Finset Point} {colour : B → Fin k}
    {a₀ b₀ c₀ : B} (h₀ : MonoTriple colour a₀ b₀ c₀) :
    ∃ a b c : B, MonoTriple colour a b c ∧
      ∀ x y z : B, MonoTriple colour x y z →
        triangleCount B a b c ≤ triangleCount B x y z := by
  classical
  let Good : ℕ → Prop := fun n ↦
    ∃ a b c : B, MonoTriple colour a b c ∧ triangleCount B a b c = n
  have hex : ∃ n, Good n :=
    ⟨triangleCount B a₀ b₀ c₀, a₀, b₀, c₀, h₀, rfl⟩
  obtain ⟨a, b, c, habc, hcount⟩ := Nat.find_spec hex
  refine ⟨a, b, c, habc, ?_⟩
  intro x y z hxyz
  rw [hcount]
  exact Nat.find_min' hex ⟨x, y, z, hxyz, rfl⟩

/-- Strict containment of triangle hulls gives strict containment of the
corresponding finite point sets as soon as one old point is exhibited outside
the new hull. -/
theorem triangleCount_lt_of_subset_of_mem_not_mem
    {B : Finset Point} {a b c x y z q : Point}
    (hsub : triangleHull x y z ⊆ triangleHull a b c)
    (hqB : q ∈ B) (hqold : q ∈ triangleHull a b c)
    (hqnew : q ∉ triangleHull x y z) :
    triangleCount B x y z < triangleCount B a b c := by
  classical
  change
    (B.filter fun p ↦ p ∈ triangleHull x y z).card <
      (B.filter fun p ↦ p ∈ triangleHull a b c).card
  apply Finset.card_lt_card
  have hfsub :
      B.filter (fun p ↦ p ∈ triangleHull x y z) ⊆
        B.filter (fun p ↦ p ∈ triangleHull a b c) := by
    intro p hp
    simp only [Finset.mem_filter] at hp ⊢
    exact ⟨hp.1, hsub hp.2⟩
  apply (Finset.ssubset_iff_of_subset hfsub).2
  refine ⟨q, ?_, ?_⟩
  · exact Finset.mem_filter.mpr ⟨hqB, hqold⟩
  · exact fun h ↦ hqnew (Finset.mem_filter.mp h).2

theorem turn_eq_zero_of_between {a b p : Point}
    (hp : p ∈ openSegment ℝ a b) :
    turn a b p = 0 := by
  rw [turn_swap_last, turn_eq_zero_of_mem_openSegment hp, neg_zero]

theorem openSegment_subset_triangleHull_left
    {a b c p : Point} (hp : p ∈ openSegment ℝ a b) :
    p ∈ triangleHull a b c := by
  exact (segment_subset_convexHull (s := ({a, b, c} : Set Point))
      (by simp) (by simp)) (openSegment_subset_segment ℝ a b hp)

/-- A point on the next side of a positively oriented triangle lies strictly
inside the supporting half-plane of the preceding side. -/
theorem turn_pos_of_mem_next_side
    {a b c p : Point} (habc : 0 < turn a b c)
    (hp : p ∈ openSegment ℝ b c) :
    0 < turn a b p := by
  apply edgeTurn_pos_of_mem_openSegment hp
  · simp
  · exact habc.le
  · exact Or.inr habc

/-- Points chosen in the relative interiors of the three sides of a
nondegenerate triangle are pairwise distinct. -/
theorem triangle_side_points_pairwise
    {a b c r s t : Point} (habc : 0 < turn a b c)
    (hr : r ∈ openSegment ℝ a b)
    (hs : s ∈ openSegment ℝ b c)
    (ht : t ∈ openSegment ℝ c a) :
    r ≠ s ∧ s ≠ t ∧ t ≠ r := by
  have hrs : r ≠ s := by
    intro e
    have hrzero := turn_eq_zero_of_between hr
    have hspos := turn_pos_of_mem_next_side habc hs
    rw [e] at hrzero
    linarith
  have hst : s ≠ t := by
    intro e
    have hszero := turn_eq_zero_of_between hs
    have htpos : 0 < turn b c t := by
      apply turn_pos_of_mem_next_side
      · rw [turn_rotate]
        exact habc
      · exact ht
    rw [e] at hszero
    linarith
  have htr : t ≠ r := by
    intro e
    have htzero := turn_eq_zero_of_between ht
    have hrpos : 0 < turn c a r := by
      apply turn_pos_of_mem_next_side
      · rw [turn_rotate, turn_rotate]
        exact habc
      · exact hr
    rw [e] at htzero
    linarith
  exact ⟨hrs, hst, htr⟩

/-- The triangle formed by one point in the relative interior of each side
has the same orientation as the original triangle. -/
theorem turn_side_points_pos
    {a b c r s t : Point} (habc : 0 < turn a b c)
    (hr : r ∈ openSegment ℝ a b)
    (hs : s ∈ openSegment ℝ b c)
    (ht : t ∈ openSegment ℝ c a) :
    0 < turn r s t := by
  rw [openSegment_eq_image] at hr hs ht
  obtain ⟨u, hu, hur⟩ := hr
  obtain ⟨v, hv, hvs⟩ := hs
  obtain ⟨w, hw, hwt⟩ := ht
  rw [← hur, ← hvs, ← hwt]
  have hid :
      turn ((1 - u) • a + u • b) ((1 - v) • b + v • c)
          ((1 - w) • c + w • a) =
        (u * v * w + (1 - u) * (1 - v) * (1 - w)) * turn a b c := by
    simp only [turn, Prod.fst_add, Prod.snd_add, Prod.smul_fst,
      Prod.smul_snd, smul_eq_mul]
    ring
  rw [hid]
  exact mul_pos
    (add_pos (mul_pos (mul_pos hu.1 hv.1) hw.1)
      (mul_pos (mul_pos (sub_pos.mpr hu.2) (sub_pos.mpr hv.2))
        (sub_pos.mpr hw.2))) habc

/-- Minimality forces the only points of the triangle carrying its colour to
be its three vertices. -/
theorem same_colour_eq_vertex_of_minimal
    {k : ℕ} {B : Finset Point} (hfour : ¬HasFourCollinear B)
    {colour : B → Fin k} (hproper : ProperBlocking B colour)
    {a b c : B} (hmono : MonoTriple colour a b c)
    (hpos : 0 < turn (a : Point) (b : Point) (c : Point))
    (hminimal : ∀ x y z : B, MonoTriple colour x y z →
      triangleCount B a b c ≤ triangleCount B x y z)
    {p : B} (hpHull : (p : Point) ∈ triangleHull a b c)
    (hpcolour : colour p = colour a) :
    p = a ∨ p = b ∨ p = c := by
  classical
  rcases hmono with ⟨hab, hbc, hca, hcab, hcbc⟩
  by_contra hp
  have hpa : p ≠ a := fun e ↦ hp (Or.inl e)
  have hpb : p ≠ b := fun e ↦ hp (Or.inr (Or.inl e))
  have hpc : p ≠ c := fun e ↦ hp (Or.inr (Or.inr e))
  have hcbp : colour b = colour p := hcab.symm.trans hpcolour.symm
  have hmono' : MonoTriple colour a b p :=
    ⟨hab, hpb.symm, hpa, hcab, hcbp⟩
  have hturnne : turn (a : Point) (b : Point) (p : Point) ≠ 0 :=
    turn_ne_zero_of_same_colour hfour hproper hab hpb.symm hpa hcab hcbp
  have hpEdges := triangle_edge_nonneg hpos.le hpHull
  have hpab : 0 < turn (a : Point) (b : Point) (p : Point) :=
    lt_of_le_of_ne hpEdges.1 (Ne.symm hturnne)
  have hcapne : turn (c : Point) (a : Point) (p : Point) ≠ 0 :=
    turn_ne_zero_of_same_colour hfour hproper hca hpa.symm hpc
      (hcab.trans hcbc).symm hpcolour.symm
  have hcap : 0 < turn (c : Point) (a : Point) (p : Point) :=
    lt_of_le_of_ne hpEdges.2.2 (Ne.symm hcapne)
  have hsub : triangleHull (a : Point) (b : Point) (p : Point) ⊆
      triangleHull (a : Point) (b : Point) (c : Point) := by
    apply triangleHull_subset_of_mem (convex_convexHull ℝ _)
    · exact subset_convexHull ℝ _ (by simp)
    · exact subset_convexHull ℝ _ (by simp)
    · exact hpHull
  have hcnew : (c : Point) ∉ triangleHull (a : Point) (b : Point) (p : Point) := by
    intro hc
    have hle : turn (a : Point) (p : Point) (c : Point) ≤ 0 := by
      apply turn_nonpos_of_mem_convexHull
          (A := ({(a : Point), (b : Point), (p : Point)} : Set Point))
      · intro q hq
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
        rcases hq with rfl | rfl | rfl
        · simp
        · rw [turn_swap_last]
          exact neg_nonpos.mpr hpab.le
        · simp
      · exact hc
    have hstrict : 0 < turn (a : Point) (p : Point) (c : Point) := by
      rw [turn_rotate]
      exact hcap
    linarith
  have hlt : triangleCount B a b p < triangleCount B a b c :=
    triangleCount_lt_of_subset_of_mem_not_mem hsub c.property
      (subset_convexHull ℝ _ (by simp)) hcnew
  exact (not_lt_of_ge (hminimal a b p hmono')) hlt

/-- The triangle formed by three relative-interior side points contains
strictly fewer points of any ambient finite set than the original triangle. -/
theorem side_triangle_count_lt
    {B : Finset Point} {a b c r s t : Point}
    (haB : a ∈ B) (habc : 0 < turn a b c)
    (hr : r ∈ openSegment ℝ a b)
    (hs : s ∈ openSegment ℝ b c)
    (ht : t ∈ openSegment ℝ c a) :
    triangleCount B r s t < triangleCount B a b c := by
  classical
  have hrHull : r ∈ triangleHull a b c :=
    openSegment_subset_triangleHull_left hr
  have hsHull : s ∈ triangleHull a b c := by
    have := openSegment_subset_triangleHull_left (c := a) hs
    rw [triangleHull_rotate a b c] at this
    exact this
  have htHull : t ∈ triangleHull a b c := by
    have := openSegment_subset_triangleHull_left (c := b) ht
    rw [triangleHull_rotate b c a, triangleHull_rotate a b c] at this
    exact this
  have hsub : triangleHull r s t ⊆ triangleHull a b c :=
    triangleHull_subset_of_mem (convex_convexHull ℝ _) hrHull hsHull htHull
  have hrzero : turn a b r = 0 := turn_eq_zero_of_between hr
  have hspos : 0 < turn a b s := turn_pos_of_mem_next_side habc hs
  have htpos : 0 < turn a b t := by
    apply edgeTurn_pos_of_mem_openSegment ht habc.le (by simp)
    exact Or.inl habc
  have hpw := triangle_side_points_pairwise habc hr hs ht
  have haNot : a ∉ triangleHull r s t := by
    intro haHull
    have haHull' :
        a ∈ convexHull ℝ (({r, s, t} : Finset Point) : Set Point) := by
      simpa [triangleHull] using haHull
    have hae : a = r := by
      apply eq_of_mem_convexHull_of_unique_turn_zero
          (A := ({r, s, t} : Finset Point)) (a := a) (b := b)
      · simp
      · intro p hp
        simp only [Finset.mem_insert, Finset.mem_singleton] at hp
        rcases hp with rfl | rfl | rfl
        · exact le_of_eq hrzero.symm
        · exact hspos.le
        · exact htpos.le
      · intro p hp hz
        simp only [Finset.mem_insert, Finset.mem_singleton] at hp
        rcases hp with rfl | rfl | rfl
        · rfl
        · exact (ne_of_gt hspos hz).elim
        · exact (ne_of_gt htpos hz).elim
      · exact haHull'
      · simp
    have hab : a ≠ b := by
      intro e
      subst b
      simp [turn] at habc
    have haopen : a ∈ openSegment ℝ a b := by simpa [hae] using hr
    exact hab ((left_mem_openSegment_iff (𝕜 := ℝ)).mp haopen)
  exact triangleCount_lt_of_subset_of_mem_not_mem hsub haB
    (subset_convexHull ℝ _ (by simp)) haNot

/-- Strict membership in all three oriented supporting half-planes. -/
def StrictlyInsideTriangle (a b c p : Point) : Prop :=
  0 < turn a b p ∧ 0 < turn b c p ∧ 0 < turn c a p

/-- The area of a triangle is the sum of the three oriented subareas cut out
by an arbitrary point. -/
theorem turn_triangle_decompose (a b c p : Point) :
    turn a b c = turn a b p + turn b c p + turn c a p := by
  simp only [turn]
  ring

/-- Closed membership in the three oriented supporting half-planes of a
positively oriented triangle. -/
def WeaklyInsideTriangle (a b c p : Point) : Prop :=
  0 ≤ turn a b p ∧ 0 ≤ turn b c p ∧ 0 ≤ turn c a p

/-- The three closed determinant inequalities characterize membership in a
positively oriented triangle. -/
theorem weaklyInsideTriangle_mem_triangleHull
    {a b c p : Point} (habc : 0 < turn a b c)
    (hp : WeaklyInsideTriangle a b c p) :
    p ∈ triangleHull a b c := by
  classical
  let w : Point → ℝ := fun q ↦
    if q = a then turn b c p / turn a b c
    else if q = b then turn c a p / turn a b c
    else if q = c then turn a b p / turn a b c
    else 0
  have hab : a ≠ b := by
    intro e
    subst b
    simp [turn] at habc
  have hac : a ≠ c := by
    intro e
    subst c
    simp [turn] at habc
  have hbc : b ≠ c := by
    intro e
    subst c
    simp only [turn] at habc
    nlinarith
  have hsum :
      turn b c p + turn c a p + turn a b p = turn a b c := by
    rw [turn_triangle_decompose a b c p]
    ring
  have hxcoord :
      turn b c p * a.1 + turn c a p * b.1 + turn a b p * c.1 =
        turn a b c * p.1 := by
    simp only [turn]
    ring
  have hycoord :
      turn b c p * a.2 + turn c a p * b.2 + turn a b p * c.2 =
        turn a b c * p.2 := by
    simp only [turn]
    ring
  have hmem :
      p ∈ convexHull ℝ ((({a, b, c} : Finset Point) : Set Point)) := by
    apply (Finset.mem_convexHull').mpr
    refine ⟨w, ?_, ?_, ?_⟩
    · intro q hq
      simp only [Finset.mem_insert, Finset.mem_singleton] at hq
      rcases hq with rfl | rfl | rfl
      · simp [w]
        exact div_nonneg hp.2.1 habc.le
      · simp [w, hab.symm]
        exact div_nonneg hp.2.2 habc.le
      · simp [w, hac.symm, hbc.symm]
        exact div_nonneg hp.1 habc.le
    · simp [w, hab, hab.symm, hac, hac.symm, hbc, hbc.symm]
      calc
        turn b c p / turn a b c + (turn c a p / turn a b c +
              turn a b p / turn a b c) =
            (turn b c p + turn c a p + turn a b p) / turn a b c := by ring
        _ = turn a b c / turn a b c := by rw [hsum]
        _ = 1 := div_self habc.ne'
    · apply Prod.ext
      · simp [w, hab, hab.symm, hac, hac.symm, hbc, hbc.symm]
        calc
          turn b c p / turn a b c * a.1 +
                (turn c a p / turn a b c * b.1 +
                turn a b p / turn a b c * c.1) =
              (turn b c p * a.1 + turn c a p * b.1 +
                turn a b p * c.1) / turn a b c := by ring
          _ = (turn a b c * p.1) / turn a b c := by rw [hxcoord]
          _ = p.1 := by field_simp [habc.ne']
      · simp [w, hab, hab.symm, hac, hac.symm, hbc, hbc.symm]
        calc
          turn b c p / turn a b c * a.2 +
                (turn c a p / turn a b c * b.2 +
                turn a b p / turn a b c * c.2) =
              (turn b c p * a.2 + turn c a p * b.2 +
                turn a b p * c.2) / turn a b c := by ring
          _ = (turn a b c * p.2) / turn a b c := by rw [hycoord]
          _ = p.2 := by field_simp [habc.ne']
  simpa [triangleHull] using hmem

/-- The vertices of a triangle containing a strict-interior point are
positively oriented. -/
theorem turn_pos_of_strictlyInsideTriangle
    {a b c p : Point} (hp : StrictlyInsideTriangle a b c p) :
  0 < turn a b c := by
  rw [turn_triangle_decompose a b c p]
  linarith [hp.1, hp.2.1, hp.2.2]

/-- The strict determinant inequalities really do place the point in the
convex hull of the three vertices. -/
theorem strictlyInsideTriangle_mem_triangleHull
    {a b c p : Point} (hp : StrictlyInsideTriangle a b c p) :
    p ∈ triangleHull a b c := by
  classical
  let w : Point → ℝ := fun q ↦
    if q = a then turn b c p / turn a b c
    else if q = b then turn c a p / turn a b c
    else if q = c then turn a b p / turn a b c
    else 0
  have hD : 0 < turn a b c := turn_pos_of_strictlyInsideTriangle hp
  have hab : a ≠ b := by
    intro e
    subst b
    simp [turn] at hD
  have hac : a ≠ c := by
    intro e
    subst c
    simp [turn] at hD
  have hbc : b ≠ c := by
    intro e
    subst c
    simp only [turn] at hD
    nlinarith
  have hsum :
      turn b c p + turn c a p + turn a b p = turn a b c := by
    rw [turn_triangle_decompose a b c p]
    ring
  have hxcoord :
      turn b c p * a.1 + turn c a p * b.1 + turn a b p * c.1 =
        turn a b c * p.1 := by
    simp only [turn]
    ring
  have hycoord :
      turn b c p * a.2 + turn c a p * b.2 + turn a b p * c.2 =
        turn a b c * p.2 := by
    simp only [turn]
    ring
  have hmem :
      p ∈ convexHull ℝ ((({a, b, c} : Finset Point) : Set Point)) := by
    apply (Finset.mem_convexHull').mpr
    refine ⟨w, ?_, ?_, ?_⟩
    · intro q hq
      simp only [Finset.mem_insert, Finset.mem_singleton] at hq
      rcases hq with rfl | rfl | rfl
      · simp [w]
        exact div_nonneg hp.2.1.le hD.le
      · simp [w, hab.symm]
        exact div_nonneg hp.2.2.le hD.le
      · simp [w, hac.symm, hbc.symm]
        exact div_nonneg hp.1.le hD.le
    · simp [w, hab, hab.symm, hac, hac.symm, hbc, hbc.symm]
      calc
        turn b c p / turn a b c + (turn c a p / turn a b c +
              turn a b p / turn a b c) =
            (turn b c p + turn c a p + turn a b p) / turn a b c := by ring
        _ = turn a b c / turn a b c := by rw [hsum]
        _ = 1 := div_self hD.ne'
    · apply Prod.ext
      · simp [w, hab, hab.symm, hac, hac.symm, hbc, hbc.symm]
        calc
          turn b c p / turn a b c * a.1 +
                (turn c a p / turn a b c * b.1 +
                turn a b p / turn a b c * c.1) =
              (turn b c p * a.1 + turn c a p * b.1 +
                turn a b p * c.1) / turn a b c := by ring
          _ = (turn a b c * p.1) / turn a b c := by rw [hxcoord]
          _ = p.1 := by field_simp [hD.ne']
      · simp [w, hab, hab.symm, hac, hac.symm, hbc, hbc.symm]
        calc
          turn b c p / turn a b c * a.2 +
                (turn c a p / turn a b c * b.2 +
                turn a b p / turn a b c * c.2) =
              (turn b c p * a.2 + turn c a p * b.2 +
                turn a b p * c.2) / turn a b c := by ring
          _ = (turn a b c * p.2) / turn a b c := by rw [hycoord]
          _ = p.2 := by field_simp [hD.ne']
  simpa [triangleHull] using hmem

theorem strictlyInsideTriangle_ne_vertices
    {a b c p : Point} (hp : StrictlyInsideTriangle a b c p) :
    p ≠ a ∧ p ≠ b ∧ p ≠ c := by
  constructor
  · intro e
    subst p
    simp [StrictlyInsideTriangle, turn] at hp
  constructor
  · intro e
    subst p
    simp [StrictlyInsideTriangle, turn] at hp
  · intro e
    subst p
    simp [StrictlyInsideTriangle, turn] at hp

/-- A chord joining relative-interior points of two adjacent sides lies
strictly inside the triangle. -/
theorem strictlyInside_between_adjacent_sides
    {a b c r s p : Point} (habc : 0 < turn a b c)
    (hr : r ∈ openSegment ℝ a b)
    (hs : s ∈ openSegment ℝ b c)
    (hp : p ∈ openSegment ℝ r s) :
    StrictlyInsideTriangle a b c p := by
  have hrab : turn a b r = 0 := turn_eq_zero_of_between hr
  have hsab : 0 < turn a b s := turn_pos_of_mem_next_side habc hs
  have hrbc : 0 < turn b c r := by
    apply edgeTurn_pos_of_mem_openSegment hr
    · rw [turn_rotate]
      exact habc.le
    · simp
    · left
      rw [turn_rotate]
      exact habc
  have hsbc : turn b c s = 0 := turn_eq_zero_of_between hs
  have hrca : 0 < turn c a r := by
    apply turn_pos_of_mem_next_side
    · rw [turn_rotate, turn_rotate]
      exact habc
    · exact hr
  have hsca : 0 < turn c a s := by
    apply edgeTurn_pos_of_mem_openSegment hs
    · rw [turn_rotate, turn_rotate]
      exact habc.le
    · simp [turn]
    · left
      rw [turn_rotate, turn_rotate]
      exact habc
  exact ⟨
    edgeTurn_pos_of_mem_openSegment hp (le_of_eq hrab.symm) hsab.le (Or.inr hsab),
    edgeTurn_pos_of_mem_openSegment hp hrbc.le (le_of_eq hsbc.symm) (Or.inl hrbc),
    edgeTurn_pos_of_mem_openSegment hp hrca.le hsca.le (Or.inl hrca)⟩

/-- Joining a side point to a strict-interior point remains strict. -/
theorem strictlyInside_between_third_side_and_inside
    {a b c t u p : Point} (habc : 0 < turn a b c)
    (ht : t ∈ openSegment ℝ c a)
    (hu : StrictlyInsideTriangle a b c u)
    (hp : p ∈ openSegment ℝ t u) :
    StrictlyInsideTriangle a b c p := by
  have htab : 0 < turn a b t := by
    apply edgeTurn_pos_of_mem_openSegment ht habc.le (by simp)
    exact Or.inl habc
  have htbc : 0 < turn b c t := by
    apply turn_pos_of_mem_next_side
    · rw [turn_rotate]
      exact habc
    · exact ht
  have htca : turn c a t = 0 := turn_eq_zero_of_between ht
  exact ⟨
    edgeTurn_pos_of_mem_openSegment hp htab.le hu.1.le (Or.inl htab),
    edgeTurn_pos_of_mem_openSegment hp htbc.le hu.2.1.le (Or.inl htbc),
    edgeTurn_pos_of_mem_openSegment hp (le_of_eq htca.symm) hu.2.2.le (Or.inr hu.2.2)⟩

theorem openSegment_mem_triangleHull_of_mem
    {a b c x y p : Point} (hx : x ∈ triangleHull a b c)
    (hy : y ∈ triangleHull a b c)
    (hp : p ∈ openSegment ℝ x y) :
    p ∈ triangleHull a b c :=
  (convex_convexHull ℝ _).openSegment_subset hx hy hp

/-- With two adjacent side points and one strict-interior point, the resulting
triangle is still a strict subtriangle. -/
theorem adjacent_side_inside_triangle_count_lt
    {B : Finset Point} {a b c r s w : Point}
    (haB : a ∈ B) (habc : 0 < turn a b c)
    (hr : r ∈ openSegment ℝ a b)
    (hs : s ∈ openSegment ℝ b c)
    (hwHull : w ∈ triangleHull a b c)
    (hw : StrictlyInsideTriangle a b c w) :
    triangleCount B r s w < triangleCount B a b c := by
  classical
  have hrHull : r ∈ triangleHull a b c :=
    openSegment_subset_triangleHull_left hr
  have hsHull : s ∈ triangleHull a b c := by
    have h := openSegment_subset_triangleHull_left (c := a) hs
    rw [triangleHull_rotate a b c] at h
    exact h
  have hsub : triangleHull r s w ⊆ triangleHull a b c :=
    triangleHull_subset_of_mem (convex_convexHull ℝ _) hrHull hsHull hwHull
  have hrzero : turn a b r = 0 := turn_eq_zero_of_between hr
  have hspos : 0 < turn a b s := turn_pos_of_mem_next_side habc hs
  have haNot : a ∉ triangleHull r s w := by
    intro haHull
    have haHull' :
        a ∈ convexHull ℝ (({r, s, w} : Finset Point) : Set Point) := by
      simpa [triangleHull] using haHull
    have hae : a = r := by
      apply eq_of_mem_convexHull_of_unique_turn_zero
          (A := ({r, s, w} : Finset Point)) (a := a) (b := b)
      · simp
      · intro p hp
        simp only [Finset.mem_insert, Finset.mem_singleton] at hp
        rcases hp with rfl | rfl | rfl
        · exact le_of_eq hrzero.symm
        · exact hspos.le
        · exact hw.1.le
      · intro p hp hz
        simp only [Finset.mem_insert, Finset.mem_singleton] at hp
        rcases hp with rfl | rfl | rfl
        · rfl
        · exact (ne_of_gt hspos hz).elim
        · exact (ne_of_gt hw.1 hz).elim
      · exact haHull'
      · simp
    have hab : a ≠ b := by
      intro e
      subst b
      simp [turn] at habc
    have haopen : a ∈ openSegment ℝ a b := by simpa [hae] using hr
    exact hab ((left_mem_openSegment_iff (𝕜 := ℝ)).mp haopen)
  exact triangleCount_lt_of_subset_of_mem_not_mem hsub haB
    (subset_convexHull ℝ _ (by simp)) haNot

theorem fin3_eq_of_avoids_two {a b c d : Fin 3}
    (hab : a ≠ b) (hca : c ≠ a) (hcb : c ≠ b)
    (hda : d ≠ a) (hdb : d ≠ b) : d = c := by
  fin_cases a <;> fin_cases b <;> fin_cases c <;> fin_cases d <;> simp_all

theorem fin3_three_avoiding_one_have_equal {a r s t : Fin 3}
    (hr : r ≠ a) (hs : s ≠ a) (ht : t ≠ a) :
    r = s ∨ s = t ∨ t = r := by
  fin_cases a <;> fin_cases r <;> fin_cases s <;> fin_cases t <;> simp_all

/-- The second descent in the three-colour argument: if two consecutive side
blockers have one nonred colour and the third has the other, blocking the
equal-coloured pair twice creates a still smaller monochromatic triangle. -/
theorem paired_side_colours_contradiction
    {B : Finset Point} (hfour : ¬HasFourCollinear B)
    {colour : B → Fin 3} (hproper : ProperBlocking B colour)
    {a b c : B} (hmono : MonoTriple colour a b c)
    (hpos : 0 < turn (a : Point) (b : Point) (c : Point))
    (hminimal : ∀ x y z : B, MonoTriple colour x y z →
      triangleCount B a b c ≤ triangleCount B x y z)
    {r s t : B}
    (hr : (r : Point) ∈ openSegment ℝ (a : Point) (b : Point))
    (hs : (s : Point) ∈ openSegment ℝ (b : Point) (c : Point))
    (ht : (t : Point) ∈ openSegment ℝ (c : Point) (a : Point))
    (hcolrs : colour r = colour s) (hcoltr : colour t ≠ colour r) : False := by
  classical
  rcases hmono with ⟨hab, hbc, hca, hcab, hcbc⟩
  have hside := triangle_side_points_pairwise hpos hr hs ht
  have hrs : r ≠ s := fun e ↦ hside.1 (congrArg Subtype.val e)
  have hst : s ≠ t := fun e ↦ hside.2.1 (congrArg Subtype.val e)
  have htr : t ≠ r := fun e ↦ hside.2.2 (congrArg Subtype.val e)
  have hrNotRed : colour r ≠ colour a :=
    blocker_colour_ne hfour hproper hab hcab hr
  have hsNotRed : colour s ≠ colour a := by
    have hsnb : colour s ≠ colour b :=
      blocker_colour_ne hfour hproper hbc hcbc hs
    exact fun h ↦ hsnb (h.trans hcab)
  have htNotRed : colour t ≠ colour a := by
    have htnc : colour t ≠ colour c :=
      blocker_colour_ne hfour hproper hca (hcab.trans hcbc).symm ht
    exact fun h ↦ htnc (h.trans (hcab.trans hcbc))

  obtain ⟨u, hu⟩ := hproper r s hrs hcolrs
  have huNotRS : colour u ≠ colour r :=
    blocker_colour_ne hfour hproper hrs hcolrs hu
  have huStrict :
      StrictlyInsideTriangle (a : Point) (b : Point) (c : Point) (u : Point) :=
    strictlyInside_between_adjacent_sides hpos hr hs hu
  have hrHull : (r : Point) ∈ triangleHull a b c :=
    openSegment_subset_triangleHull_left hr
  have hsHull : (s : Point) ∈ triangleHull a b c := by
    have h := openSegment_subset_triangleHull_left (c := (a : Point)) hs
    rw [triangleHull_rotate (a : Point) (b : Point) (c : Point)] at h
    exact h
  have huHull : (u : Point) ∈ triangleHull a b c :=
    openSegment_mem_triangleHull_of_mem hrHull hsHull hu
  have huNotRed : colour u ≠ colour a := by
    intro hured
    rcases same_colour_eq_vertex_of_minimal hfour hproper
        ⟨hab, hbc, hca, hcab, hcbc⟩ hpos hminimal huHull hured with h | h | h
    · exact (strictlyInsideTriangle_ne_vertices huStrict).1
        (congrArg Subtype.val h)
    · exact (strictlyInsideTriangle_ne_vertices huStrict).2.1
        (congrArg Subtype.val h)
    · exact (strictlyInsideTriangle_ne_vertices huStrict).2.2
        (congrArg Subtype.val h)
  have hcolut : colour u = colour t := by
    exact fin3_eq_of_avoids_two hrNotRed.symm htNotRed hcoltr
      huNotRed huNotRS
  have htu : t ≠ u := by
    intro e
    have htzero : turn (c : Point) (a : Point) (t : Point) = 0 :=
      turn_eq_zero_of_between ht
    have : (t : Point) = (u : Point) := congrArg Subtype.val e
    rw [this] at htzero
    linarith [huStrict.2.2]

  obtain ⟨w, hw⟩ := hproper t u htu hcolut.symm
  have hwNotT : colour w ≠ colour t :=
    blocker_colour_ne hfour hproper htu hcolut.symm hw
  have hwStrict :
      StrictlyInsideTriangle (a : Point) (b : Point) (c : Point) (w : Point) :=
    strictlyInside_between_third_side_and_inside hpos ht huStrict hw
  have htHull : (t : Point) ∈ triangleHull a b c := by
    have h := openSegment_subset_triangleHull_left (c := (b : Point)) ht
    rw [triangleHull_rotate (b : Point) (c : Point) (a : Point),
      triangleHull_rotate (a : Point) (b : Point) (c : Point)] at h
    exact h
  have hwHull : (w : Point) ∈ triangleHull a b c :=
    openSegment_mem_triangleHull_of_mem htHull huHull hw
  have hwNotRed : colour w ≠ colour a := by
    intro hwred
    rcases same_colour_eq_vertex_of_minimal hfour hproper
        ⟨hab, hbc, hca, hcab, hcbc⟩ hpos hminimal hwHull hwred with h | h | h
    · exact (strictlyInsideTriangle_ne_vertices hwStrict).1
        (congrArg Subtype.val h)
    · exact (strictlyInsideTriangle_ne_vertices hwStrict).2.1
        (congrArg Subtype.val h)
    · exact (strictlyInsideTriangle_ne_vertices hwStrict).2.2
        (congrArg Subtype.val h)
  have hcolwr : colour w = colour r := by
    exact fin3_eq_of_avoids_two htNotRed.symm hrNotRed hcoltr.symm
      hwNotRed hwNotT
  have hrw : r ≠ w := by
    intro e
    have hrzero : turn (a : Point) (b : Point) (r : Point) = 0 :=
      turn_eq_zero_of_between hr
    have : (r : Point) = (w : Point) := congrArg Subtype.val e
    rw [this] at hrzero
    linarith [hwStrict.1]
  have hsw : s ≠ w := by
    intro e
    have hszero : turn (b : Point) (c : Point) (s : Point) = 0 :=
      turn_eq_zero_of_between hs
    have : (s : Point) = (w : Point) := congrArg Subtype.val e
    rw [this] at hszero
    linarith [hwStrict.2.1]
  have hmono' : MonoTriple colour r s w :=
    ⟨hrs, hsw, hrw.symm, hcolrs, hcolrs.symm.trans hcolwr.symm⟩
  have hlt : triangleCount B r s w < triangleCount B a b c :=
    adjacent_side_inside_triangle_count_lt a.property hpos hr hs hwHull hwStrict
  exact (not_lt_of_ge (hminimal r s w hmono')) hlt

/-- The minimal-triangle descent, with the chosen triangle already oriented
counterclockwise. -/
theorem no_monoTriple_of_minimal_oriented
    {B : Finset Point} (hfour : ¬HasFourCollinear B)
    {colour : B → Fin 3} (hproper : ProperBlocking B colour)
    {a b c : B} (hmono : MonoTriple colour a b c)
    (hpos : 0 < turn (a : Point) (b : Point) (c : Point))
    (hminimal : ∀ x y z : B, MonoTriple colour x y z →
      triangleCount B a b c ≤ triangleCount B x y z) : False := by
  classical
  rcases hmono with ⟨hab, hbc, hca, hcab, hcbc⟩
  obtain ⟨r, hr⟩ := hproper a b hab hcab
  obtain ⟨s, hs⟩ := hproper b c hbc hcbc
  obtain ⟨t, ht⟩ := hproper c a hca (hcab.trans hcbc).symm
  have hside := triangle_side_points_pairwise hpos hr hs ht
  have hrs : r ≠ s := fun e ↦ hside.1 (congrArg Subtype.val e)
  have hst : s ≠ t := fun e ↦ hside.2.1 (congrArg Subtype.val e)
  have htr : t ≠ r := fun e ↦ hside.2.2 (congrArg Subtype.val e)
  have hrNotRed : colour r ≠ colour a :=
    blocker_colour_ne hfour hproper hab hcab hr
  have hsNotRed : colour s ≠ colour a := by
    have hsnb : colour s ≠ colour b :=
      blocker_colour_ne hfour hproper hbc hcbc hs
    exact fun h ↦ hsnb (h.trans hcab)
  have htNotRed : colour t ≠ colour a := by
    have htnc : colour t ≠ colour c :=
      blocker_colour_ne hfour hproper hca (hcab.trans hcbc).symm ht
    exact fun h ↦ htnc (h.trans (hcab.trans hcbc))
  have hpigeon : colour r = colour s ∨ colour s = colour t ∨
      colour t = colour r :=
    fin3_three_avoiding_one_have_equal hrNotRed hsNotRed htNotRed
  rcases hpigeon with hrscol | hstcol | htrcol
  · by_cases htrne : colour t ≠ colour r
    · exact paired_side_colours_contradiction hfour hproper
        ⟨hab, hbc, hca, hcab, hcbc⟩ hpos hminimal hr hs ht hrscol htrne
    · have htrcol' : colour t = colour r := not_ne_iff.mp htrne
      have hmono' : MonoTriple colour r s t :=
        ⟨hrs, hst, htr, hrscol, hrscol.symm.trans htrcol'.symm⟩
      have hlt := side_triangle_count_lt a.property hpos hr hs ht
      exact (not_lt_of_ge (hminimal r s t hmono')) hlt
  · by_cases hrsne : colour r ≠ colour s
    · have hmonoRot : MonoTriple colour b c a :=
        ⟨hbc, hca, hab, hcbc, (hcab.trans hcbc).symm⟩
      have hposRot : 0 < turn (b : Point) (c : Point) (a : Point) := by
        rw [turn_rotate]
        exact hpos
      have hcountRot : triangleCount B b c a = triangleCount B a b c := by
        unfold triangleCount
        rw [triangleHull_rotate]
      have hminimalRot : ∀ x y z : B, MonoTriple colour x y z →
          triangleCount B b c a ≤ triangleCount B x y z := by
        intro x y z hxyz
        rw [hcountRot]
        exact hminimal x y z hxyz
      exact paired_side_colours_contradiction hfour hproper hmonoRot hposRot
        hminimalRot hs ht hr hstcol hrsne
    · have hrscol : colour r = colour s := not_ne_iff.mp hrsne
      have hmono' : MonoTriple colour r s t :=
        ⟨hrs, hst, htr, hrscol, hstcol⟩
      have hlt := side_triangle_count_lt a.property hpos hr hs ht
      exact (not_lt_of_ge (hminimal r s t hmono')) hlt
  · by_cases hstne : colour s ≠ colour t
    · have hmonoRot : MonoTriple colour c a b :=
        ⟨hca, hab, hbc, (hcab.trans hcbc).symm, hcab⟩
      have hposRot : 0 < turn (c : Point) (a : Point) (b : Point) := by
        rw [turn_rotate, turn_rotate]
        exact hpos
      have hcountRot : triangleCount B c a b = triangleCount B a b c := by
        unfold triangleCount
        rw [triangleHull_rotate (b : Point) (c : Point) (a : Point),
          triangleHull_rotate (a : Point) (b : Point) (c : Point)]
      have hminimalRot : ∀ x y z : B, MonoTriple colour x y z →
          triangleCount B c a b ≤ triangleCount B x y z := by
        intro x y z hxyz
        rw [hcountRot]
        exact hminimal x y z hxyz
      exact paired_side_colours_contradiction hfour hproper hmonoRot hposRot
        hminimalRot ht hr hs htrcol hstne
    · have hstcol : colour s = colour t := not_ne_iff.mp hstne
      have hmono' : MonoTriple colour r s t :=
        ⟨hrs, hst, htr, htrcol.symm.trans hstcol.symm, hstcol⟩
      have hlt := side_triangle_count_lt a.property hpos hr hs ht
      exact (not_lt_of_ge (hminimal r s t hmono')) hlt

/-- A properly three-coloured finite blocking set with no four collinear
points has no monochromatic triple. -/
theorem no_monoTriple_three_colours
    {B : Finset Point} (hfour : ¬HasFourCollinear B)
    {colour : B → Fin 3} (hproper : ProperBlocking B colour)
    {a₀ b₀ c₀ : B} (h₀ : MonoTriple colour a₀ b₀ c₀) : False := by
  classical
  obtain ⟨a, b, c, hmono, hminimal⟩ := exists_minimal_monoTriple h₀
  rcases hmono with ⟨hab, hbc, hca, hcab, hcbc⟩
  have hturnne : turn (a : Point) (b : Point) (c : Point) ≠ 0 :=
    turn_ne_zero_of_same_colour hfour hproper hab hbc hca hcab hcbc
  rcases lt_or_gt_of_ne hturnne with hneg | hpos
  · have hmonoSwap : MonoTriple colour a c b :=
      ⟨hca.symm, hbc.symm, hab.symm, hcab.trans hcbc, hcbc.symm⟩
    have hposSwap : 0 < turn (a : Point) (c : Point) (b : Point) := by
      rw [turn_swap_last]
      linarith
    have hcountSwap : triangleCount B a c b = triangleCount B a b c := by
      unfold triangleCount
      rw [triangleHull_swap_last]
    have hminimalSwap : ∀ x y z : B, MonoTriple colour x y z →
        triangleCount B a c b ≤ triangleCount B x y z := by
      intro x y z hxyz
      rw [hcountSwap]
      exact hminimal x y z hxyz
    exact no_monoTriple_of_minimal_oriented hfour hproper hmonoSwap
      hposSwap hminimalSwap
  · exact no_monoTriple_of_minimal_oriented hfour hproper
      ⟨hab, hbc, hca, hcab, hcbc⟩ hpos hminimal

/-- Corollary 2.2: a properly three-coloured blocking set has at most six
points. -/
theorem card_le_six_of_three_coloured_blocking
    (B : Finset Point) (hfour : ¬HasFourCollinear B)
    (colour : B → Fin 3) (hproper : ProperBlocking B colour) :
    B.card ≤ 6 := by
  classical
  have hfiber : ∀ d : Fin 3,
      ((Finset.univ : Finset B).filter fun p ↦ colour p = d).card ≤ 2 := by
    intro d
    by_contra hle
    have hlt : 2 < ((Finset.univ : Finset B).filter fun p ↦ colour p = d).card :=
      Nat.lt_of_not_ge hle
    obtain ⟨a, ha, b, hb, c, hc, hab, hac, hbc⟩ := Finset.two_lt_card.mp hlt
    have hca : c ≠ a := hac.symm
    have hcab : colour a = colour b := by
      simpa using (Finset.mem_filter.mp ha).2.trans (Finset.mem_filter.mp hb).2.symm
    have hcbc : colour b = colour c := by
      simpa using (Finset.mem_filter.mp hb).2.trans (Finset.mem_filter.mp hc).2.symm
    exact no_monoTriple_three_colours hfour hproper
      ⟨hab, hbc, hca, hcab, hcbc⟩
  have hcard : (Finset.univ : Finset B).card =
      ∑ d ∈ (Finset.univ : Finset (Fin 3)),
        ((Finset.univ : Finset B).filter fun p ↦ colour p = d).card := by
    apply Finset.card_eq_sum_card_fiberwise
    intro p hp
    simp
  calc
    B.card = (Finset.univ : Finset B).card := by simp
    _ = ∑ d ∈ (Finset.univ : Finset (Fin 3)),
        ((Finset.univ : Finset B).filter fun p ↦ colour p = d).card := hcard
    _ ≤ ∑ _d ∈ (Finset.univ : Finset (Fin 3)), 2 := by
      exact Finset.sum_le_sum fun d _ ↦ hfiber d
    _ = 6 := by norm_num

end Lax56Proofs.HKBTriangle
