import Lax56Proofs.ValtrCoverSetup
import Lax56Proofs.ValtrConvexRun

namespace Lax56Proofs.ValtrRadialOrder

open Lax56.Geometry Lax56.ConvexLayers
open Lax56Proofs.ConvexLayers Lax56Proofs.CupsCapsGeometry
open Lax56Proofs.Orientation Lax56Proofs.HKBGeometry Lax56Proofs.HKBTriangle
open Lax56Proofs.ValtrExtension Lax56Proofs.ValtrCyclic Lax56Proofs.ValtrConvexRun
open Lax56Proofs.ValtrSectorSetup Lax56Proofs.ValtrCoverSetup
open scoped Classical

def CyclicTriple {n : ℕ} (i j k : Fin n) : Prop :=
  (i < j ∧ j < k) ∨ (j < k ∧ k < i) ∨ (k < i ∧ i < j)

theorem turn_pos_of_cyclic_triple {n : ℕ} {v : Fin n → Point}
    (htri : ∀ i j k, i < j → j < k → 0 < turn (v i) (v j) (v k))
    {i j k : Fin n} (h : CyclicTriple i j k) :
    0 < turn (v i) (v j) (v k) := by
  rcases h with h | h | h
  · exact htri _ _ _ h.1 h.2
  · rw [← turn_rotate]; exact htri _ _ _ h.1 h.2
  · rw [turn_rotate]; exact htri _ _ _ h.1 h.2

theorem radial_triangle_side {d a b p q : Point}
    (hp : p ∈ triangleHull d a b) (hpos : 0 < turn d q p) :
    0 < turn d q a ∨ 0 < turn d q b := by
  by_contra hh
  push Not at hh
  have hnonpos : turn d q p ≤ 0 := by
    apply turn_nonpos_of_mem_convexHull (A := ({d, a, b} : Set Point)) _ hp
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl | rfl
    · simp
    · exact hh.1
    · exact hh.2
  linarith

/-- Three fan triangles in cyclic order cannot put the middle selected
ray after both neighboring rays. Otherwise a line through the center
would alternate sides four times on the outer polygon. -/
theorem not_two_reverse_radial_sides {n : ℕ} [NeZero n] {v : Fin n → Point}
    (htri : ∀ i j k, i < j → j < k → 0 < turn (v i) (v j) (v k))
    {i j k : Fin n} (hijk : CyclicTriple i j k) {d p q r : Point}
    (hp : p ∈ triangleHull d (v i) (v (i + 1)))
    (hq : StrictlyInsideTriangle d (v j) (v (j + 1)) q)
    (hr : r ∈ triangleHull d (v k) (v (k + 1)))
    (hpq : turn d p q < 0) (hqr : turn d q r < 0) : False := by
  have hp' : 0 < turn d q p := by rw [turn_swap_last]; exact neg_pos.mpr hpq
  have hleft := radial_triangle_side hp hp'
  have hj : turn d q (v j) < 0 := by
    rw [turn_swap_last]; exact neg_neg_of_pos hq.1
  have hjnext : 0 < turn d q (v (j + 1)) := by
    rw [turn_rotate]; exact hq.2.2
  have ha : ∃ a : Fin n, (a = i ∨ a = i + 1) ∧ 0 < turn d q (v a) := by
    rcases hleft with h | h
    · exact ⟨i, Or.inl rfl, h⟩
    · exact ⟨i + 1, Or.inr rfl, h⟩
  have hb : ∃ b : Fin n, (b = k ∨ b = k + 1) ∧ turn d q (v b) < 0 := by
    have hneg : turn d q (v k) < 0 ∨ turn d q (v (k + 1)) < 0 := by
      by_contra hh
      push Not at hh
      have hnonneg : 0 ≤ turn d q r := by
        apply turn_nonneg_of_mem_convexHull (A := ({d, v k, v (k + 1)} : Set Point)) _ hr
        intro x hx
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with rfl | rfl | rfl
        · simp
        · exact hh.1
        · exact hh.2
      linarith
    rcases hneg with h | h
    · exact ⟨k, Or.inl rfl, h⟩
    · exact ⟨k + 1, Or.inr rfl, h⟩
  obtain ⟨a, hai, ha⟩ := ha
  obtain ⟨b, hbk, hb⟩ := hb
  have haj : a ≠ j := by intro h; rw [h] at ha; linarith
  have hbnext : b ≠ j + 1 := by intro h; rw [h] at hb; linarith
  have hab : a ≠ b := by intro h; rw [h] at ha; linarith
  have hiN := cyclic_next_cases i
  have hjN := cyclic_next_cases j
  have hkN := cyclic_next_cases k
  have hord : CyclicTriple a j (j + 1) ∧ CyclicTriple a j b ∧
      CyclicTriple a (j + 1) b ∧ CyclicTriple j (j + 1) b := by
    unfold CyclicTriple at hijk ⊢
    have hajv : a.val ≠ j.val := fun h ↦ haj (Fin.ext h)
    have hbnextv : b.val ≠ (j + 1).val := fun h ↦ hbnext (Fin.ext h)
    have habv : a.val ≠ b.val := fun h ↦ hab (Fin.ext h)
    rcases hai with rfl | rfl <;> rcases hbk with rfl | rfl <;>
      omega
  exact not_alternating_line_sides (turn_pos_of_cyclic_triple htri hord.1)
    (turn_pos_of_cyclic_triple htri hord.2.1)
    (turn_pos_of_cyclic_triple htri hord.2.2.1)
    (turn_pos_of_cyclic_triple htri hord.2.2.2) ha hj hjnext hb

/-- Two successive positive radial turns determine the orientation of
three extreme points. A reversed turn would put the middle vertex in a
triangle generated by the center and the other two points. -/
theorem turn_pos_of_two_radial_sides {Q : Finset Point} {d p q r : Point}
    (hq : q ∈ extremeLayer Q) (hd : d ∈ Q) (hp : p ∈ Q) (hr : r ∈ Q)
    (hpq : 0 < turn d p q) (hqr : 0 < turn d q r) : 0 < turn p q r := by
  by_contra hh
  have hh := le_of_not_gt hh
  have hid : turn p q r = turn d p q + turn d q r - turn d p r := by
    unfold turn; ring
  have hpr : 0 < turn d p r := by linarith
  apply extreme_not_mem_triangle hq hd hp hr
    (by rintro rfl; simp at hpq)
    (by rintro rfl; simp at hpq)
    (by rintro rfl; simp at hqr)
  apply weaklyInsideTriangle_mem_triangleHull hpr
  refine ⟨hpq.le, ?_, ?_⟩
  · rw [turn_swap_last]; exact neg_nonneg.mpr hh
  · rw [← turn_rotate]; exact hqr.le

/-- The radial-order comparison needs only the three selected fan
triangles, not a selection at every index of the outer cycle. -/
theorem radial_extreme_triple {Q : Finset Point} (hgen : ¬HasThreeCollinear Q)
    {n : ℕ} [NeZero n] {v : Fin n → Point}
    (htri : ∀ i j k, i < j → j < k → 0 < turn (v i) (v j) (v k))
    {i j k : Fin n} (hij : i < j) (hjk : j < k)
    {d p q r : Point} (hd : d ∈ inner Q)
    (hp : p ∈ extremeLayer Q) (hq : q ∈ extremeLayer Q) (hr : r ∈ extremeLayer Q)
    (hpFan : StrictlyInsideTriangle d (v i) (v (i + 1)) p)
    (hqFan : StrictlyInsideTriangle d (v j) (v (j + 1)) q)
    (hrFan : StrictlyInsideTriangle d (v k) (v (k + 1)) r) : 0 < turn p q r := by
  have hdQ : d ∈ Q := inner_subset Q hd
  have hdc {a : Point} (ha : a ∈ extremeLayer Q) : d ≠ a := by
    intro heq
    exact (Finset.mem_sdiff.mp hd).2 (heq.symm ▸ ha)
  have hpq : p ≠ q := by
    intro heq
    apply (ne_of_lt hij)
    apply radial_triangle_index_eq htri hpFan
    rwa [heq]
  have hqr : q ≠ r := by
    intro heq
    apply (ne_of_lt hjk)
    apply radial_triangle_index_eq htri hqFan
    rwa [heq]
  have hpr : p ≠ r := by
    intro heq
    apply (ne_of_lt (hij.trans hjk))
    apply radial_triangle_index_eq htri hpFan
    rwa [heq]
  have hn₁ := turn_ne_zero_of_generalPosition hgen hdQ (extremeLayer_subset Q hp)
    (extremeLayer_subset Q hq) (hdc hp) (hdc hq) hpq
  have hn₂ := turn_ne_zero_of_generalPosition hgen hdQ (extremeLayer_subset Q hq)
    (extremeLayer_subset Q hr) (hdc hq) (hdc hr) hqr
  have hn₃ := turn_ne_zero_of_generalPosition hgen hdQ (extremeLayer_subset Q hr)
    (extremeLayer_subset Q hp) (hdc hr) (hdc hp) hpr.symm
  have hn₁₂ : ¬(turn d p q < 0 ∧ turn d q r < 0) := by
    rintro ⟨ha, hb⟩
    exact not_two_reverse_radial_sides htri (Or.inl ⟨hij, hjk⟩)
      (strictlyInsideTriangle_mem_triangleHull hpFan) hqFan
      (strictlyInsideTriangle_mem_triangleHull hrFan) ha hb
  have hn₂₃ : ¬(turn d q r < 0 ∧ turn d r p < 0) := by
    rintro ⟨ha, hb⟩
    exact not_two_reverse_radial_sides htri (Or.inr (Or.inr ⟨hij, hjk⟩))
      (strictlyInsideTriangle_mem_triangleHull hqFan) hrFan
      (strictlyInsideTriangle_mem_triangleHull hpFan) ha hb
  have hn₃₁ : ¬(turn d r p < 0 ∧ turn d p q < 0) := by
    rintro ⟨ha, hb⟩
    exact not_two_reverse_radial_sides htri (Or.inr (Or.inl ⟨hij, hjk⟩))
      (strictlyInsideTriangle_mem_triangleHull hrFan) hpFan
      (strictlyInsideTriangle_mem_triangleHull hqFan) ha hb
  by_cases h₁ : 0 < turn d p q
  · by_cases h₂ : 0 < turn d q r
    · exact turn_pos_of_two_radial_sides hq hdQ (extremeLayer_subset Q hp) (extremeLayer_subset Q hr) h₁ h₂
    have h₂ : turn d q r < 0 := lt_of_le_of_ne (le_of_not_gt h₂) hn₂
    have h₃ : 0 < turn d r p := by
      by_contra hh
      exact hn₂₃ ⟨h₂, lt_of_le_of_ne (le_of_not_gt hh) hn₃⟩
    rw [turn_rotate]
    exact turn_pos_of_two_radial_sides hp hdQ (extremeLayer_subset Q hr) (extremeLayer_subset Q hq) h₃ h₁
  · have h₁ : turn d p q < 0 := lt_of_le_of_ne (le_of_not_gt h₁) hn₁
    have h₂ : 0 < turn d q r := by
      by_contra hh
      exact hn₁₂ ⟨h₁, lt_of_le_of_ne (le_of_not_gt hh) hn₂⟩
    have h₃ : 0 < turn d r p := by
      by_contra hh
      exact hn₃₁ ⟨lt_of_le_of_ne (le_of_not_gt hh) hn₃, h₁⟩
    rw [← turn_rotate]
    exact turn_pos_of_two_radial_sides hr hdQ (extremeLayer_subset Q hq) (extremeLayer_subset Q hp) h₂ h₃

/-- Radial selections from the extreme points of an inner polygon have
the same cyclic order as the outer fan triangles. This is a determinant
proof of radial-order agreement, without angles or a circle construction. -/
theorem cyclic_triples_of_radial_extreme_points {Q : Finset Point}
    (hgen : ¬HasThreeCollinear Q) {n : ℕ} [NeZero n] {v c : Fin n → Point}
    (htri : ∀ i j k, i < j → j < k → 0 < turn (v i) (v j) (v k))
    {d : Point} (hd : d ∈ inner Q) (hc : ∀ i, c i ∈ extremeLayer Q)
    (hfan : ∀ i, StrictlyInsideTriangle d (v i) (v (i + 1)) (c i)) :
    ∀ i j k, i < j → j < k → 0 < turn (c i) (c j) (c k) := by
  have hcinj : Function.Injective c := by
    intro i j heq
    apply radial_triangle_index_eq htri (hfan i)
    rw [heq]
    exact hfan j
  have hdQ : d ∈ Q := inner_subset Q hd
  have hcQ (i) : c i ∈ Q := extremeLayer_subset Q (hc i)
  have hdc (i) : d ≠ c i := by
    intro heq
    exact (Finset.mem_sdiff.mp hd).2 (heq.symm ▸ hc i)
  have hne (i j) (hij : i ≠ j) : turn d (c i) (c j) ≠ 0 :=
    turn_ne_zero_of_generalPosition hgen hdQ (hcQ i) (hcQ j)
      (hdc i) (hdc j) (hcinj.ne hij)
  intro i j k hij hjk
  have hn₁ := hne i j (ne_of_lt hij)
  have hn₂ := hne j k (ne_of_lt hjk)
  have hn₃ := hne k i (ne_of_gt (hij.trans hjk))
  have hnot (a b e : Fin n) (horder : CyclicTriple a b e) :
      ¬(turn d (c a) (c b) < 0 ∧ turn d (c b) (c e) < 0) := by
    rintro ⟨hab, hbe⟩
    exact not_two_reverse_radial_sides htri horder
      (strictlyInsideTriangle_mem_triangleHull (hfan a)) (hfan b)
      (strictlyInsideTriangle_mem_triangleHull (hfan e)) hab hbe
  have hn₁₂ := hnot i j k (Or.inl ⟨hij, hjk⟩)
  have hn₂₃ := hnot j k i (Or.inr (Or.inr ⟨hij, hjk⟩))
  have hn₃₁ := hnot k i j (Or.inr (Or.inl ⟨hij, hjk⟩))
  by_cases h₁ : 0 < turn d (c i) (c j)
  · by_cases h₂ : 0 < turn d (c j) (c k)
    · exact turn_pos_of_two_radial_sides (hc j) hdQ (hcQ i) (hcQ k) h₁ h₂
    have h₂ : turn d (c j) (c k) < 0 := lt_of_le_of_ne (le_of_not_gt h₂) hn₂
    have h₃ : 0 < turn d (c k) (c i) := by
      by_contra hh
      exact hn₂₃ ⟨h₂, lt_of_le_of_ne (le_of_not_gt hh) hn₃⟩
    rw [turn_rotate]
    exact turn_pos_of_two_radial_sides (hc i) hdQ (hcQ k) (hcQ j) h₃ h₁
  · have h₁ : turn d (c i) (c j) < 0 := lt_of_le_of_ne (le_of_not_gt h₁) hn₁
    have h₂ : 0 < turn d (c j) (c k) := by
      by_contra hh
      exact hn₁₂ ⟨h₁, lt_of_le_of_ne (le_of_not_gt hh) hn₂⟩
    have h₃ : 0 < turn d (c k) (c i) := by
      by_contra hh
      exact hn₃₁ ⟨lt_of_le_of_ne (le_of_not_gt hh) hn₃, h₁⟩
    rw [← turn_rotate]
    exact turn_pos_of_two_radial_sides (hc k) hdQ (hcQ j) (hcQ i) h₂ h₃

/-- Specialization to Valtr's selected third-layer apices when every
radial triangle is defined. -/
theorem apex_cyclic_triples {S : Finset Point} (hgen : ¬HasThreeCollinear S)
    {n : ℕ} [NeZero n] {v c : Fin n → Point}
    (htri : ∀ i j k, i < j → j < k → 0 < turn (v i) (v j) (v k))
    {d : Point} (hd : d ∈ inner (inner (inner S)))
    (hdata : ∀ i, ApexData S v d i (c i)) :
    ∀ i j k, i < j → j < k → 0 < turn (c i) (c j) (c k) := by
  apply cyclic_triples_of_radial_extreme_points (Q := inner (inner S)) _ htri hd
    (fun i ↦ (hdata i).mem_third) (fun i ↦ (hdata i).strict_triangle)
  exact fun h ↦ hgen (hasThreeCollinear_mono
    ((inner_subset (inner S)).trans (inner_subset S)) h)

end Lax56Proofs.ValtrRadialOrder
